- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  tasks:
# tasks file for wp-dependencies
  - name: Update packages (this is equivalent to yum update -y)
    yum:
      name: '*'
      state:  latest
  - name: Install dependencies for WordPress
    yum: 
      name: "{{ packages }}"
      #state: present
    vars:
      packages:
      - nginx 
      - mysql-server 
      - mysql
      - php71
      - mysql55-server
      - php71-mysqlnd
      - php71-mbstring
      - php71-gd
      - MySQL-python27
      - python
  - name: Ensure MariaDB is running (and enable it at boot)
    service: name=mysqld state=started enabled=yes

  - name: Create mysqlDB database
    mysql_db: 
      name: wp_mysql_db 
      state: present
  - name: crear usuario para wordpress
    mysql_user:
      name: wp_user
      password: 12345
      priv: '*.*:ALL'
      state: present
  
  - name: Descarga Wordpress
    get_url:
      url=https://wordpress.org/latest.tar.gz
      dest=/tmp/wordpress.tar.gz
      validate_certs=no
  - name: Extract WordPress
    unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html/ copy=no
    become: yes

  - name: Update default nginx site
    become: yes
    lineinfile: 
      path: /etc/nginx/nginx.conf.default 
      regexp: "(.)+root /usr/share/nginx/html"
      line: "root /var/www/html/wordpress"
    notify:
      - restart nginx

  - name: Copy sample config file
    command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php creates=/var/www/html/wordpress/wp-config.php
    become: yes
  - name: chkconfig nginx
    service:
      name: nginx
      enabled: yes
  #roles:
    #- server
    #- mysql
    #- nginx
    #- php-fpm
    #- wordpress
