- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  tasks:
# tasks file for wp-dependencies
  - name: Update packages (this is equivalent to yum update -y)
    yum:
      name: '*'
      state:  latest
  - name: Install dependencies for WordPress
    yum: 
      name: "{{ packages }}"
      #state: present
    vars:
      packages:
      - nginx 
      - mysql-server 
      - mysql
      - php71
      - mysql55-server
      - php71-mysqlnd
      - php71-mbstring
      - MySQL-python27
      - python
  - name: Ensure MariaDB is running (and enable it at boot)
    service: name=mysqld state=started enabled=yes

  - name: Create mysqlDB database
    mysql_db: 
      name: wp_mysql_db 
      state: present
  - name: crear usuario para wordpress
    mysql_user:
      name: wp_user
      password: 12345
      priv: '*.*:ALL'
      state: present
  #roles:
    #- server
    #- mysql
    #- nginx
    #- php-fpm
    #- wordpress
